version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld:latest
  helloworld1:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld:latest
  helloworld2:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld:latest
