version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld:latest
  helloworld1:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld1:latest
  helloworld2:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld2:latest
  helloworld3:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld3:latest
  helloworld4:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld4:latest
  helloworld5:
    lang: go
    handler: ./helloworld
    image: ashkan52/helloworld5:latest
